org: nabilshaikhnabil
app: serverless-project-app
service: post-service

frameworkVersion: ">=2.39.0"

plugins:
  - serverless-mocha-plugin

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  profile: personal
  region: ap-southeast-2
  environment:
    POST_TABLE: post-service-dev
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"

functions:
  createPost:
    handler: api/post.create
    memorySize: 128
    description: Create post
    events:
      - http: 
          path: post
          method: post
          cors: true
  listPosts: 
    handler: api/post.list
    memorySize: 128
    description: List all posts
    events:
      - http: 
          path: post
          method: get 
          cors: true
  deletePost: 
    handler: api/post.deletePost
    memorySize: 128
    description: delete post by id
    events:
      - http: 
          path: post
          method: delete 
          cors: true

resources: 
  Resources: 
    PostsDynamoDbTable: 
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties: 
        AttributeDefinitions: 
          - 
            AttributeName: "id"
            AttributeType: "S"
        KeySchema: 
          - 
            AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput: 
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification: 
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: ${self:provider.environment.POST_TABLE}